# -=-=-= Data files =-=-=-
# placeholders:
# (PluginDirectory) The directory where the plugin stores its configuration

# The location of the folder to store player data in
player-data-folder: (PluginDirectory)/playerdata

# The location of the currencies.yml file
currencies-file: (PluginDirectory)/currencies.yml

# -=-=-= Data management =-=-=-

# Load the player data as soon as the player join.
# This makes it so that the data is avaliable immediately
# but also keeps the data of all online player in memory
preload-player-data: true

# Unload the players data when they quit the server.
# Do not disable this unless you have another plugin that unloads the
# data for you or the data of all player that have joined will be kept in memory
unload-data-on-quit: true

# Save the players data when they quit.
# This will not have any effect if unload-data-on-quit is disabled
save-data-on-quit: true

# Save data on server shutdown.
save-data-on-shutdown: true

# Save data on transaction
# If disabled the players data wont be written
# on every transaction. This will cause lower disk IO
# but if the server crashes or loses power the player
# data might not be saved
save-data-on-transaction: true

# -=-=-= Commands =-=-=-
# Enable the command for the plugin
enable-dynamic-currencies-command: true

# Aliases for the command
dynamic-currencies-command-aliases: ['dc']


# -=-=-= Other =-=-=-
# Print debug messages in the console
print-debug-info: false

# The service priority for vault
vault-service-priority: 'Normal'